### ISSUE TITLE
index.js:12655 Uncaught TypeError: Cannot read properties of undefined (reading 'theme')

### ISSUE THREAD

**Issue by suhli** [antvis/F2#1437]
- [x] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/f2-zb36pz?file=/index.html)

### Steps to reproduce
打开
https://zb36pz.csb.app/

| Environment | Info |
|---|---|
| f2 | 4.0.12 |
| System | macos 12.1 |
| Browser | Google Chrome 100.0.4896.60 |

---
```
index.js:12655 Uncaught TypeError: Cannot read properties of undefined (reading 'theme')
    at Chart.getStyle (index.js:12655:28)
    at new Chart (index.js:12598:24)
    at window.onload ((index):216:24)
```

**Comment by suhli** [comment]
> 请问怎么解决的

应该是文档的版本有问题,看另外一个版本的文档就好了,我忘了
