### ISSUE TITLE
uniapp项目vue2版本使用npm install @antv/f2 --save安装后引入组件报错

### ISSUE THREAD

**Issue by dakedou** [antvis/F2#1901]
- [ ] I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/dakedou/online](https://github.com/dakedou/online)

### Steps to reproduce
引入@antv/f2后报错 。错误内容TypeError: (0 , _tslib.__spreadArray) is not a function
    at DefaultStyleValueRegistry.registerMetadata (pages-demo-demo.js:26413:261)
    at pages-demo-demo.js:26413:134
    at Array.forEach (<anonymous>)
    at new DefaultStyleValueRegistry (pages-demo-demo.js:26413:101)
    at Object.<anonymous> (pages-demo-demo.js:27243:466)
    at Object.RfGs (pages-demo-demo.js:27892:30)
    at __webpack_require__ (index.js:854:30)
    at fn (index.js:151:20)
    at Object.ep9H (pages-demo-demo.js:35150:14)
    at __webpack_require__ (index.js:854:30)

| Environment | Info |
|---|---|
| f2 | 5.0.39 |
| System | - |
| Browser | 谷歌最新版 |

---
报错问题可能出现在_tslib.__spreadArray  。 本地打印_tslib.只有_tslib.__spreadArrays为什么项目中出现spreadArray 。期待尽快给与回复

**Comment by mycodemanager** [comment]
到现在还是没有解决，请问你那边最后用的什么方案

**Comment by hi-pengyu** [comment]
> 到现在还是没有解决，请问你那边最后用的什么方案

请问解决了吗

**Comment by hi-pengyu** [comment]
> * [ ]  I have searched the [issues](https://github.com/antvis/f2/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> 
> https://github.com/dakedou/online
> 
> ### Steps to reproduce
> 
> 引入@antv/f2后报错 。错误内容TypeError: (0 , _tslib.__spreadArray) is not a function at DefaultStyleValueRegistry.registerMetadata (pages-demo-demo.js:26413:261) at pages-demo-demo.js:26413:134 at Array.forEach () at new DefaultStyleValueRegistry (pages-demo-demo.js:26413:101) at Object. (pages-demo-demo.js:27243:466) at Object.RfGs (pages-demo-demo.js:27892:30) at **webpack_require** (index.js:854:30) at fn (index.js:151:20) at Object.ep9H (pages-demo-demo.js:35150:14) at **webpack_require** (index.js:854:30)
> 
> Environment	Info
> f2	5.0.39
> System	-
> Browser	谷歌最新版
> 报错问题可能出现在_tslib.__spreadArray 。 本地打印_tslib.只有_tslib.__spreadArrays为什么项目中出现spreadArray 。期待尽快给与回复

请问解决了吗

**Comment by mycodemanager** [comment]
| |
y18519502582
|
|
也没有
|


---- 回复的原邮件 ----
| 发件人 | Kevin ***@***.***> |
| 发送日期 | 2025年04月7日 08:48 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [antvis/F2] uniapp项目vue2版本使用npm install @antv/f2 --save安装后引入组件报错 (Issue #1901) |

到现在还是没有解决，请问你那边最后用的什么方案

请问解决了吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

hi-pengyu left a comment (antvis/F2#1901)

到现在还是没有解决，请问你那边最后用的什么方案

请问解决了吗

**Comment by huxiguo** [comment]
+1 好几年了这个问题还没有解决,小程序用不了

**Comment by leewr** [comment]
你好,你的来信我已收到我会尽快与你取得联系。
 此信件自动发送，表示我已收到您的来信！文润个人博客天街雨站www.leewr.com
